inventory.py

This PR makes changes to the Canvas API course data fetching so that it employs the recommended strategy for pagination, utilizing the link headers. The code now uses the `get_next_page` method on the `ApiUtil` class to get the proper parameters for the next request. To enable this change, I modified `make_request_using_api_utils` so that it returns a `requests.Response` object rather than the parsed data. This PR aims to resolve issue #11.

Use ApiUtil.get_next_page for paging (#11)

---

db/migrations/0004.add_sis_id.py
db/migrations/0004.add_um_id.py
inventory.py

This PR makes adds a migration and makes modifications to the existing UDW user query in order to add `user.sis_id` (a user's UM ID) to the database. It pulls the `sis_id` from the `sis_user_id` column of the `pseudonym_dim` table. Some processing is done to ensure that the value is an integer. The cases where they are not seem to be for friend accounts, where the value is an email. This PR aims to resolve issue #22.

Add sis_id to user table (#22)

---

db/db_creator.py

This PR changes `db_creator` to pass the MySQL database password string through `quote_plus` (from `urllib.parse`) before using it in the connection string to ensure that special characters do not disrupt authentication. The PR aims to resolve issue #46.
I tested this by adding a problematic character to the password in `docker-compose.yml`, deleting the `.data` directory, and changing the password in my mapped `env.json`. It failed without the change and succeeded with it.

Use quote_plus on db password string (#46)

---

canvas/published_date.py

Problem: member variable string gets treated as Tuple in Python
Since I declared then as such. This PR should fix this case.
This is not a bug but minor annoyance
https://stackoverflow.com/questions/27654671/member-variable-string-gets-treated-as-tuple-in-python

Fix the member variables treating as tuple

---

course_inventory/inventory.py
db/migrations/0011.add_course_sis_ids.py

This PR adds a migration and modifies `course_inventory/inventory.py` in order to add and populate `sis_id` columns in the `course` and `course_section` tables of the database. In addition, I modified an existing UDW query to use the `params` parameter of `pd.read_sql`, hopefully resolving a SQL injection warning raised by Codacy. Also, I modified the existing `process_sis_id` mapping function so it could be used to also drop non-integer SIS ID values for sections. This PR aims to resolve issue #42.
Resolves #42.

Add sis_id columns to course and course_section tables (#42)

---

run_jobs.py

This PR makes minor changes to `run_jobs.py` to correct a mistake where `started_at_dt` was being logged instead of `finished_at_dt` (also, it was misspelled `finshed_at_dt`). Note that the values being stored in the database are still correct. This PR resolves issue #86.

Correct logged finished_at value and fix typo in run_jobs.py (#86)

---

README.md
course_inventory/inventory.py
run_jobs.py
vocab.py

This PR pulls out the enumerations from `run_jobs.py` into a separate `vocab.py` module so that both `run_jobs.py` and job-specific modules can reference the enumeration without introducing a circular dependency. It also changes the format of the `data_source` dictionaries returned from job entry functions so that the value associated with the key `data_source_name` is a member of `ValidDataSourceName`. This PR aims to resolve #96.

Pull enumerations from run_jobs.py into separate vocab.py module (#96)

---

course_inventory/inventory.py

This PR makes a small change that aims to avoid errors by moving from a hardcoded-index-based approach to a name-based approach for identifying and pulling the `canvasdatadate` value from the UDW's `unizin_metadata` table. This PR aims to resolve issue #103.

Identify and pull canvasdatadate using key name and value column (#103)

---

db/db_creator.py

I was able to test this on all the following scenarios
1. Miserver instance: Tesla
2. Localhost mysql DB instance
3. From Docker compose build
Resolves #88.

#88 enabling SSL to support connections within MiServer

---

run_jobs.py

This PR modifies the sleep mechanism for use with `docker-compose` so that the database check happens before the `time.sleep(1)`. The PR aims to resolves #105.

Move sleep until after MySQL container check (#105)

---

README.md

This PR changes the Codacy badge in the README so the organization in use matches the legacy organization in use by our other projects. The PR aims to resolve issue #107.

Update Codacy badge to use legacy organization (for now) (#107)

---

mivideo/mivideo_extract.py

Fixes #111.
Specify the units of the source timestamp so Pandas will convert it to a string representation correctly.

fix MiVideo `data_updated_at` timestamp (#111)

---

config/env_blank.json
course_inventory/inventory.py
create_db.py
db/db_creator.py
mivideo/mivideo_extract.py
run_jobs.py

This PR makes changes to `DBCreator`, and usages, to resolve a few issues that have accumulated related to the class. The issues and how they were resolved are described below in the task list. The PR aims to resolve issues #66, #84, and #109.

Improve DBCreator (#66, #84, #109)

---

README.md
config/env_blank.json
course_inventory/inventory.py
db/migrations/0013.add_term_table.py
db/migrations/0014.change_course_sis_id_data_type.py
online_meetings/canvas_zoom_meetings.py

This PR modifies the `COURSE_INVENTORY`job and the database schema as to be able to collect and store data related to multiple academic terms. Some additional details are provided in the task list below. This PR aims to resolve issues #113 and #117.

Add term table, accomodate multiple terms, fix course.sis_id bug (#113, #117)

---

course_inventory/inventory.py
db/db_creator.py

This PR modifies two existing parameters in the constructor of `DBCreator` and the function `make_request_using_api_utils` from `course_inventory/inventory` to avoid the default mutable parameter value anti-pattern described [here](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html) and flagged by Codacy. These changes do not appear to have any downstream effects on data produced. The PR aims to resolve issue #120.

Switch to using sentinel values for two parameters in db_creator, inventory (#120)

---

requirements.txt

This PR updates `requirements.txt` to remove dependencies no longer in use, bump versions for bugfix releases, pin `requests`, and alphabetize entries. More details are provided in the task list below. The PR aims to resolve issue #139.

Update requirements.txt (#139)

---

course_inventory/async_enroll_gatherer.py

This PR makes small modifications to the usages of [`pd.DataFrame.drop_duplicates`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html) in `AsyncEnrollGatherer.generate_output()` to avoid the possibility of duplicate primary keys (which can occur if a name or other field changed during the process, resulting in two slightly different records before duplicates are dropped). This possibility was avoided with the use of `subset=['canvas_id']` as a parameter to `drop_duplicates`, which will mean that only `canvas_id` (the PK) is considered when identifying duplicates. In addition, to ensure the latest changes are kept, the parameter `keep='last'` was also added. These changes were made to `enrollment` and `section` as well as `user` out of an …

Fix duplicate dropping in AsyncEnrollGatherer (#145)

---

course_inventory/inventory.py
db/migrations/0019.relax_sis_ids.py

To resolve insertion errors and create consistency, this PR changes via a migration two SIS ID fields (`course_section.sis_id` and `account.sis_id`) to the `VARCHAR(256)` data type in the database, mirroring the Canvas data model. (Note that the `course.sis_id` was previously changed to this type in PR #160.) The PR also removes a mapping function previously used to normalize `course_section.sis_id`, as well as an unnecessary string conversion call in the `slim_down_course_data` function (the data was already a string). The PR aims to resolve issue #165.

Relax data types of SIS IDs (#165)

---

course_inventory/inventory.py

Similar to PR #146, this PR adds duplicate dropping to the creation of `course` records to avoid possible errors when inserting into the database. The modifications include the use of `pd.DataFrame.drop_duplicates` with the `subset` parameter to limit duplicate consideration to the PK (`canvas_id`) and the `keep` parameter to ensure the second record found is kept. This change is responding to incidents in the production and test processes where a different course in each process seems to have been duplicated. The PR aims to resolve issue #174.

Handle possibility of duplicate courses being inserted to `course` table (#174)

---

course_inventory/inventory.py

This small PR changes the path construction for writing CSV files to use the constant `DATA_DIR` (containing an absolute path to the `data` directory) from `environ.py`. This ensures that the correct path is always used, even if the location of the file or where its functions/methods are executed from changes.

Use DATA_DIR instead of "data" for CSV output path in inventory.py (#178)

---

course_inventory/inventory.py
course_inventory/published_date.py

Fixes #156 , #21 
This PR addresses the 
1. retry logic when the canvas is sending 500/504 and 
1. Retrying for each course (failed with HTTP error or JSON error) 3 times in case of error 
encounted. I have never seen any API error due to JSON parsing.
2. Average Success response time is 0-30 sec. The gateway timeout error takes about 1minutes. That's the max amount of the time that is taking
2. Only fetch those published dates with new courses added as part of API call and that from the database don't have a date
Test case went through:
-  With an empty database
-  Some dates already in DB ( with both null and not null published date) and few more to 
fetch as part of new courses
I tried to apply a timeout to request and response. But Not effective. Especially with a response timeout …

I156 better published date

---

course_inventory/inventory.py

This PR modifies the `make_request_using_api_utils` function from `inventory.py` -- used by the `course`, `account`, and `term` Canvas data fetching -- so that it exits the program if the maximum number of attempts are reached. This ensures that the `Response` object returned by the function is always a valid one. The PR aims to resolve issue #161.
I thought for a little while about whether the program should continue after failing multiple times, and I decided that for these requests, the dataset would be incomplete without the data. We would either be missing 100 courses or a foreign key constraint would fail from `course` -> `account` or `term`. Note that I have not yet seen this situation in our deployed processes; if we are concerned that this might happen, we can bump the max …

Exit if max attempt limit is reached in make_request_using_api_utils (#161)

---

.dockerignore

This PR updates the repo's `.dockerignore` file to ensure unnecessary and sensitive files are not included in Docker images built locally. Changes include use of the `**/` Docker-specific syntax to properly find files with certain patterns in any directory; widening of the `env` pattern to capture HJSON configuration files; and the removal of the `.vscode` directory from the list (as it might be needed in our deployment environments). The PR aims to resolve issue #180.

Update .dockerignore (#180)

---

mivideo/mivideo_extract.py

Fixes #188.
Because the regex wasn't explicit enough, Kaltura categories with hexadecimal values (e.g., "Canvas_UMich>site>channels>5430bafe907cca901a0f11646470dd64244ebd5f") would have all digits following the first non-integer digit stripped and the remaining ones (i.e., "5430") were incorrectly treated as the Canvas course ID.  The regex now specifically looks for integer digits, optionally followed by ">InContext", and the end of the string. 
I **_humbly_** request that comments on this PR be nested under a single review per reviewer.  It helps me when the comments are organized this way, especially if the comments request changes in the code.
If I've requested a review from you but you are definitely unable to review this PR, please leave a comment saying so (please state _why_ …

Fix MiVideo course ID conversion bug (#188)

---

db/migrations/0021.add_mivideo_fk.py

Resolves #183.
Add relationships between `mivideo_media_courses` and `mivideo_media_created` tables.
I **_humbly_** request that comments on this PR be nested under a single review per reviewer. It helps me when the comments are organized this way, especially if the comments request changes in the code.
If I've requested a review from you but you are definitely unable to review this PR, please leave a comment saying so (please state why you're unable to review, that would be appreciated), tell the other reviewers that the review will be left to them, and remove your name from the list of reviewers.

define MiVideo table relationships (#183)

---

mivideo/mivideo_extract.py

Resolves #150.
Simplifies the transformation of Kaltura media categories to Canvas course ID numbers and removes dependency on regular expressions.  Both make it easier for maintainers to understand.
* Don't rename the `categories` column to `course_id` immediately.  Create the new column by transforming the data, then delete the old column.  Maybe not as efficient, but easier to understand.
* Avoid using Pandas' `str` property of `Series` objects.  Use `map()` instead, which is something maintainers will probably be familiar with from base Python, JavaScript, and other languages.  🎩 @ssciolla 
* Replace regular expression use with splitting category strings on `>`, the delimiter Kaltura uses in its category hierarchies.
* Probably improved efficiency in the removal of non-decimal course …

Improve MiVideo course ID parsing (#150)
